"""added avatars, artwork, and comments

Revision ID: 1cc9d966b6b2
Revises: e2568781fcd1
Create Date: 2021-05-19 09:53:28.960544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc9d966b6b2'
down_revision = 'e2568781fcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('artwork', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('projects', 'artwork')
    # ### end Alembic commands ###
